apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- solucao-api.dep.yaml
- solucao-api.svc.yaml

namespace: demo-danweb

images:
- name: williambr2022/demo-agenda-back
  newName: williambr2022/demo-agenda-back
  newTag: d9e5a4ac6b29c334c9c3a8bb7a5e99d8b4480f05
