apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- solucao-api.dep.yaml
- solucao-api.svc.yaml

namespace: demo-danweb

images:
- name: williambr2022/demo-agenda-back
  newName: williambr2022/demo-agenda-back
  newTag: eaf5c700105232e83fa36400e4b803d82aab67a2
