apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- solucao-api.dep.yaml
- solucao-api.svc.yaml

namespace: demo-danweb

images:
- name: williambr2022/demo-agenda-back
  newName: williambr2022/demo-agenda-back
  newTag: 8db3e10e53d740e6b87e008aa4957db79572d89a
