insert into AttributeTypes ([key], [value]) VALUES ('Texto','string')
insert into AttributeTypes ([key], [value]) VALUES ('Data','datetime')
insert into AttributeTypes ([key], [value]) VALUES ('Hora','time')
insert into AttributeTypes ([key], [value]) VALUES ('Decimal','decimal')
insert into AttributeTypes ([key], [value]) VALUES ('Decimal Extenso','decimal_extenso')
insert into AttributeTypes ([key], [value]) VALUES ('Data Extenso','datetime_extenso')
insert into AttributeTypes ([key], [value]) VALUES ('Hora Extenso','time_extenso')

insert into TechnicalAttributes ([key], [value]) VALUES ('Hora Início','StartTime')
insert into TechnicalAttributes ([key], [value]) VALUES ('Hora Término','EndTime')
insert into TechnicalAttributes ([key], [value]) VALUES ('Nome Locatário','Client.Name')
insert into TechnicalAttributes ([key], [value]) VALUES ('Nome Equipamento','Equipament.Name')
insert into TechnicalAttributes ([key], [value]) VALUES ('Data Locação','Date')
insert into TechnicalAttributes ([key], [value]) VALUES ('Valor','Value')
insert into TechnicalAttributes ([key], [value]) VALUES ('Tempo Locação','RentalTime')
insert into TechnicalAttributes ([key], [value]) VALUES ('Ponteira1','Additional1')
insert into TechnicalAttributes ([key], [value]) VALUES ('Valor Sem Ponteira','ValueWithoutSpec')
insert into TechnicalAttributes ([key], [value]) VALUES ('Desconto','Discount')
insert into TechnicalAttributes ([key], [value]) VALUES ('Frete','Freight')

insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('ca1b62d3-30c1-4df9-8297-2116f8a96e5e','#HoraInicio', 'StartTime', 'time',0,1)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('43644b11-9150-4c58-81ac-3640b42ac473','#HoraTermino', 'EndTime', 'time',0,2)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('01ea2b18-04bf-4588-9925-4bec23d3756b','#NomeLocatario', 'Client.Name', 'string',0,3)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('c8e5d713-5c71-45c7-b2af-b758619c310c','#DataLocacaoExtenso', 'Date', 'datetime_extenso',0,4)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('af53bf1d-de2f-44d3-86f9-fc6d1323eec6','#ValorLocacaoExtenso', 'Value', 'decimal_extenso',0,5)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('e9adc18e-5886-460d-85af-4c223c24d1e4','#FreteExtenso', 'Freight', 'decimal_extenso',0,6)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('5c0aa420-5ac5-49b0-bcf4-aed0086964e1','#DescontoExtenso', 'Discount', 'decimal_extenso',0,7)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('c4ec81a5-d5f8-479e-bc06-2a2d80d60ec6','#ValorTotalExtenso', 'TotalValue', 'decimal_extenso',0,8)

insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('6671d7da-8829-4638-8332-fecb9bf6694b','#ValorLocacao', 'Value', 'decimal',0,9)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('b25a53db-c41f-4672-a979-8399999c6ee6','#DataLocacao', 'Date', 'datetime',0),10
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('6fb52746-a866-40e1-a8f4-53640bf15858','#TempoLocacao', 'RentalTime', 'time_extenso',0,11)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('7a8e7506-3630-42bc-bd55-90ae7cf54010','#Frete', 'Freight', 'decimal',0,12)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('cd5a1630-1803-45ce-903d-28741d17e456','#Desconto', 'Discount', 'decimal',0,13)
insert into ModelAttributes (id,fileAttribute,technicalAttribute,AttributeType,active) VALUES ('aab60812-3780-4aad-81a9-d6a9607a71d2','#ValorTotal', 'TotalValue', 'decimal',0,14)